# This is a basic workflow to help you get started with Actions

name: BicepBuild

on:
  push:
    paths: 
      - "/bicep"
      - "/.github/workflows/bicepBuild.yml"
      

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ContextCheck
        shell: pwsh
        run: dir

      - name: Install Bicep
        shell: pwsh
        run: |
          az install bicep

      - name: ChangeDir
        shell: pwsh
        run: cd bicep
          
      - name: Bicep build
        shell: pwsh
        run: bicep build --file main.json --outdir compiled/
