# This is a basic workflow to help you get started with Actions

name: BicepBuild

on:
  push:
    branches:
      - main
      
    paths: 
      - "/bicep"
      - "/.github/workflows/bicepBuild.yml"
      
  pull_request:
    branches:
      - main

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Bicep
        run: |
          az bicep install

      - name: ChangeDir
        run: cd bicep
          
      - name: Bicep build
        run: bicep build --file main.json --outdir compiled/
