# This is a basic workflow to help you get started with Actions

name: BicepBuild

on:
  push:
    branches:
      - main
      - master
      
    paths: 
      - "/bicep"
      - "/.github/workflows/bicepBuild.yml"
      
  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

       steps:
      - uses: actions/checkout@v2

      - name: ContextCheck
        shell: pwsh
        run: dir

      - name: Install Bicep
        shell: pwsh
        run: |
          az bicep install
      - name: ChangeDir
        shell: pwsh
        run: cd bicep

      - name: Bicep build
        shell: pwsh
        run: /home/runner/.azure/bin/bicep build --file main.json --outdir compiled/
