# This is a basic workflow to help you get started with Actions

name: BicepBuild

on:
  push:
    paths: 
      - "/bicep"
      - "/.github/workflows/bicepBuild.yml"
      

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ContextCheck
        shell: pwsh
        run: dir

      - name: Install Bicep
        shell: pwsh
        run: |
          # Check Bicep versions available
          $uri = "https://api.github.com/repos/Azure/bicep/releases"
          $headers = @{ Accept = "application/vnd.github.v3+json" }
          $releases = Invoke-RestMethod -Method GET -Uri $uri -Headers $headers
          if (($Version -eq "latest") -or ($Version -eq $null)) {
              $release = ($releases | Select-Object -Property tag_name | Sort-Object -Descending)[0]
          } else {
              $release = ($releases | Where-Object { $_.tag_name -like $Version.Replace("x", "*") } | Select-Object -Property tag_name | Sort-Object -Descending)[0]
          }
          $uri = "https://github.com/Azure/bicep/releases/download/$($release.tag_name)/bicep-linux-x64"
          
          # Fetch the given version of Bicep CLI binary
          curl $uri
          
          # Mark it as executable
          chmod +x  bicep-linux-x64
          
          # Add bicep to your PATH (requires admin)
          sudo mv ./bicep-linux-x64 /usr/local/bin/bicep
          
          # Verify you can now access the 'bicep' command
          bicep --help
          
      - name: Bicep build
        shell: pwsh
        run: bicep build --file bicep/main.json --outdir bicep/compiled/
