# This is a basic workflow to help you get started with Actions

name: BicepBuild

on:
  push:
    paths: 
      - "/bicep"
      - "/.github/workflows/bicepBuild.yml"
      

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ContextCheck
        shell: pwsh
        run: dir

      - name: Install Bicep
        shell: pwsh
        run: |
          az bicep install
          
          write-output "Verifying bicep can be run"
          bicep --help
          
      - name: Bicep build
        shell: pwsh
        run: bicep build --file bicep/main.json --outdir bicep/compiled/
