name: ByoVnetCI
# Credential prerequisites
# 1. IAM Owner on the Resource Group you're deploying into
# 2. IAM Owner on the Resource Group with vnet



on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Byo Vnet Aks Bicep run

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds:  ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false
          
      - name: Azure CLI Action
        uses: Azure/cli@1.0.4
        with:
          inlineScript: |
            RG='Automation-Actions-AksDeployCI'
            RESNAME='AksByo'
            DEPNAME='Dep${{ github.run_number }}'
            az deployment group create -f main.bicep -g $RG -p "AksDeploy-ByoVnet.parameters.json" -p resourceName=$RESNAME --name $DEPNAME
            
            AKSNAME=$(az aks list -g Automation-Actions-AksDeployCI --query "[].[name]" -o tsv)
            APPMANIFEST='https://raw.githubusercontent.com/Gordonby/AKS-K8S-Lab-L200/master/azure-vote-all-in-one-redis.yaml'
            az aks get-credentials -g $RG -n $AKSNAME --admin
            kubectl apply -f $APPMANIFEST

